language: node_js

node_js:
  - '8'

script:
  - npm test
  - npm run build

before_install:
- mkdir ./build  
- openssl aes-256-cbc -K $encrypted_917a2a1d3be4_key -iv $encrypted_917a2a1d3be4_iv
  -in BigRedButton-8fc659339eef.json.enc -out ./build/BigRedButton-8fc659339eef.json -d

before_deploy:
  - cp ./app.yaml ./build
  - cp ./package.json ./build
  - cd ./build

deploy:
  default: true
  skip_cleanup: true
  provider: gae
  project: "bigredbutton-165918"
  keyfile: "BigRedButton-8fc659339eef.json"
  message: "Build # $TRAVIS_BUILD_NUMBER"
      