language: node_js
node_js:
- '8'
cache: npm
script:
- npm test
- npm run build
- npm run deploy
after_script: npm run alias
env:
  global:
    secure: Liclq05vs94ZfMhNFfq/FqaaSb2TuZG7H0wtg2aRQzqHWfvyPwaapNZi6H+0el2615Lyp7XHKJSC1y4ikYsEEtVSGBqkU16omkjaljZLY980SbOKDB6sArmMcwgG4oC4fcc2XVIjO9APzV5Mk6DPS5MYwrAg5J3Qs8ydW0KpZJs5Kbeepl+rtlJg1i4qKv7RhH29f2UEj0HPxYVea2A12/hd/4zOfH6pB+NgjniXO11v270UVBwekZ+LdWiqOgqej+Mx4oKn7FWKHb5QRFoGcxZ4RCopdpeOR7W8JbetWFIDJk3aTewz4Kl0gCpS+3K7kTeGQylhrjvAAQUsnGRSOKtv75pTlp0sxhB2ZXIqliE58htGPryB8Hu0uFMLVkECA1bhRinqZIjixDSJCfS5L0AoN04SBCHFse5wpMAVe6ewEcyAwiq0XhStp27usYKpvU4neOOs80E+KXw5qcAgbxMTzD+e/V6mapBhxyi39Xk9zSCMfaKxVj133YMTgrNpmNWdHLIsueCJPZm7I2gZWgutOpz7HXn5sPpB1RT/mDQoRjIhWzApWM8Onc+KFoDrNmHs5oI4fgBfHJJaS+NPhXDjcib/LU7kx1hq96OFLPyuaiTs6/xXJUq656MfZGy3QPEqD+xFpjn6CgVom9tMcAz8bf845lv2FSzihVXMMic=
before_install:
- openssl aes-256-cbc -K $encrypted_917a2a1d3be4_key -iv $encrypted_917a2a1d3be4_iv
  -in ./src/data/firebase/firebaseServiceAccount.privateKey.json.enc -out ./src/data/firebase/firebaseServiceAccount.privateKey.json
  -d
