runtime: nodejs
env: flex

env_variables:
  SUBSCRIPTIONS_HOST: wss://bigredbutton-165918.appspot.com

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# resources:
#  cpu: .5
#  memory_gb: 0.18
#  disk_size_gb: 10