import mongoose from 'mongoose';

const Schema = mongoose;

const schema = new Schema({
  // unique id is generated by mongo.
  company: {
    type: String,
    required: true,
  },

  name: {
    type: String,
    required: true,
  },

  shortDescription: {
    type: String,
  },

  description: {
    type: String,
    required: true,
  },

  version: {
    type: String,
    required: true,
    unique: true,
  },
  startDate: {
    type: Date,
    required: true,
  },
  endDate: {
    type: Date,
    required: true,
  },

  location: {
    type: Schema.Types.ObjectId,
    ref: 'Address',
  },
  speakers: [
    {
      type: Schema.Types.ObjectId,
      ref: 'Speaker',
    },
  ],
  sessions: [
    {
      type: Schema.Types.ObjectId,
      ref: 'Session',
    },
  ],
  sponsors: [
    {
      type: Schema.Types.ObjectId,
      ref: 'Sponsor',
    },
  ],
});

export default mongoose.model('Event', schema);
